# Generated by Django 3.0.4 on 2021-07-23 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=500)),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'All Profiles',
                'verbose_name_plural': 'All Profiles',
            },
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=1000, verbose_name='Password')),
                ('comment', models.TextField(blank=True)),
                ('notification', models.CharField(blank=True, max_length=1000)),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.CityData')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopkeepers Profile',
                'verbose_name_plural': 'Shopkeepers Profile',
            },
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=1000, verbose_name='Password')),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('suspend_account', models.BooleanField(default=False)),
                ('can_change_photo', models.BooleanField(default=False, verbose_name='Can Change Photo')),
                ('share', models.IntegerField(default=0)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.CityData')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Person',
                'verbose_name_plural': 'Sales Person',
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=1000, verbose_name='Password')),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('comes_under', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SalesPerson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profile',
            },
        ),
        migrations.CreateModel(
            name='CustomerLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=15)),
                ('mobile', models.CharField(default='XXXXXXXXXX', max_length=15)),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Login Info',
                'verbose_name_plural': 'Customer Login Info',
            },
        ),
    ]
