# Generated by Django 3.0.4 on 2021-08-13 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=1000, verbose_name='Password')),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('per_design_profit', models.IntegerField(default=0, verbose_name='Per Design Cost')),
                ('date_of_joining', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profile',
            },
        ),
        migrations.CreateModel(
            name='RewardScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField(default=0)),
                ('total_sale', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0, verbose_name='Time Duration in Days')),
                ('total_rewards', models.IntegerField(default=0, verbose_name='Reward')),
            ],
            options={
                'verbose_name': 'Reward Scheme',
                'verbose_name_plural': 'Reward Scheme',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=500)),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'All Profiles',
                'verbose_name_plural': 'All Profiles',
            },
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pwd', models.CharField(max_length=1000, verbose_name='Password')),
                ('comment', models.TextField(blank=True)),
                ('notification', models.CharField(blank=True, max_length=1000)),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.CityData')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopkeepers Profile',
                'verbose_name_plural': 'Shopkeepers Profile',
            },
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pwd', models.CharField(max_length=1000, verbose_name='Password')),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('suspend_account', models.BooleanField(default=False)),
                ('can_change_photo', models.BooleanField(default=False, verbose_name='Can Change Photo')),
                ('share', models.IntegerField(default=0)),
                ('security_code', models.CharField(blank=True, max_length=4)),
                ('security_warning', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.CityData')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Person',
                'verbose_name_plural': 'Sales Person',
            },
        ),
        migrations.CreateModel(
            name='RewardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=1000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reward', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward History',
                'verbose_name_plural': 'Reward History',
            },
        ),
        migrations.CreateModel(
            name='FreelancerEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('earning', models.IntegerField(blank=True, default=0)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Freelancer')),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='comes_under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SalesPerson'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Designcomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=3000)),
                ('shopdetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.ShopDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design Comments',
                'verbose_name_plural': 'Design Comments',
            },
        ),
        migrations.CreateModel(
            name='CustomerLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=15)),
                ('mobile', models.CharField(default='XXXXXXXXXX', max_length=15)),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Login Info',
                'verbose_name_plural': 'Customer Login Info',
            },
        ),
    ]
