# Generated by Django 3.0.4 on 2021-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='comes_under',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='comes_under',
            field=models.ManyToManyField(to='users.SalesPerson'),
        ),
    ]
