# Generated by Django 3.0.4 on 2021-07-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='security_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
