# Generated by Django 3.0.4 on 2020-10-13 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_files_activated_till'),
        ('users', '0002_remove_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.CityData'),
            preserve_default=False,
        ),
    ]
