# Generated by Django 3.0.4 on 2021-07-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_salesperson_security_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='security_warning',
            field=models.BooleanField(default=False),
        ),
    ]
