# Generated by Django 3.0.4 on 2021-07-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_salesperson_security_warning'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField(default=0)),
                ('total_sale', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0, verbose_name='Time Duration in Days')),
                ('total_rewards', models.IntegerField(default=0, verbose_name='Reward')),
            ],
            options={
                'verbose_name': 'Reward Scheme',
                'verbose_name_plural': 'Reward Scheme',
            },
        ),
    ]
