# Generated by Django 3.0.4 on 2020-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
