# Generated by Django 3.0.4 on 2020-12-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_resources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20201203_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=1000, verbose_name='Password')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.CityData')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Person',
                'verbose_name_plural': 'Sales Person',
            },
        ),
        migrations.AddField(
            model_name='freelancer',
            name='comes_under',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SalesPerson'),
        ),
    ]
