# Generated by Django 3.0.4 on 2020-10-19 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0009_auto_20201016_2132'),
        ('users', '0005_remove_userprofile_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'All Profiles', 'verbose_name_plural': 'All Profiles'},
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=1000)),
                ('comment', models.TextField(blank=True)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.CityData')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopkeepers Profile',
                'verbose_name_plural': 'Shopkeepers Profile',
            },
        ),
    ]
