# Generated by Django 3.0.4 on 2021-01-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201204_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
