# Generated by Django 3.0.4 on 2021-07-29 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rewardhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardhistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
