# Generated by Django 3.0.4 on 2021-08-26 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usernotificati'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotificati',
            options={'verbose_name': 'Users Notification', 'verbose_name_plural': 'Users Notification'},
        ),
        migrations.AddField(
            model_name='usernotificati',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificati',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
