# Generated by Django 3.0.4 on 2020-10-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201019_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='pwd',
            field=models.CharField(max_length=1000, verbose_name='Password'),
        ),
    ]
