# Generated by Django 3.0.4 on 2021-08-26 04:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20210826_1009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNotificati',
            new_name='UserNotification',
        ),
    ]
