# Generated by Django 3.0.4 on 2021-01-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210104_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
