# Generated by Django 3.0.4 on 2021-08-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210729_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
