# Generated by Django 3.0.4 on 2021-01-08 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20210104_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='boff@3^12', max_length=15)),
                ('mobile', models.CharField(default='XXXXXXXXXX', max_length=15)),
                ('otp', models.IntegerField(default=0)),
                ('is_varified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Login Info',
                'verbose_name_plural': 'Customer Login Info',
            },
        ),
    ]
