# Generated by Django 3.0.4 on 2021-08-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_salesperson_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
