# Generated by Django 3.0.4 on 2021-08-27 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210826_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationalert',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
