# Generated by Django 3.0.4 on 2021-01-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customerlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogin',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
