# Generated by Django 3.0.4 on 2021-08-03 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210803_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('earning', models.IntegerField(blank=True, default=0)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Freelancer')),
            ],
        ),
    ]
