# Generated by Django 3.0.4 on 2021-03-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_salesperson_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='suspend_account',
            field=models.BooleanField(default=False),
        ),
    ]
