# Generated by Django 3.0.4 on 2021-09-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_userprofile_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthYear', models.CharField(max_length=20)),
                ('prize', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Winners',
                'verbose_name_plural': 'Monthly Winners',
            },
        ),
    ]
