# Generated by Django 3.0.4 on 2021-04-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_salesperson_suspend_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='can_change_photo',
            field=models.BooleanField(default=False, verbose_name='Can Change Photo'),
        ),
    ]
