# Generated by Django 3.0.4 on 2021-08-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_designcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designcomments',
            old_name='by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='designcomments',
            name='to',
        ),
    ]
