# Generated by Django 3.0.4 on 2021-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_monthlywinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='coupon_code',
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
