# Generated by Django 3.0.4 on 2021-08-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20210803_1736'),
        ('users', '0012_auto_20210804_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcomments',
            name='shopdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.ShopDetails'),
        ),
    ]
