# Generated by Django 3.0.4 on 2021-07-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_shopdetails_created_by'),
        ('users', '0012_salesperson_can_change_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.CityData'),
        ),
    ]
