# Generated by Django 3.0.4 on 2021-09-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210902_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlywinner',
            name='user',
        ),
        migrations.AddField(
            model_name='monthlywinner',
            name='customers',
            field=models.ManyToManyField(to='users.CustomerLogin'),
        ),
    ]
