# Generated by Django 3.0.4 on 2021-08-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_designcomments_shopdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='per_design_profit',
            field=models.IntegerField(default=0),
        ),
    ]
