# Generated by Django 3.0.4 on 2021-07-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210719_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='assigned_freelancer',
        ),
    ]
