# Generated by Django 3.0.4 on 2021-08-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_freelancer_per_design_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='per_design_profit',
            field=models.IntegerField(default=0, verbose_name='Per Design Cost'),
        ),
    ]
