# Generated by Django 3.0.4 on 2021-07-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_salesperson_assigned_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='share',
            field=models.IntegerField(default=0),
        ),
    ]
