# Generated by Django 3.0.4 on 2021-07-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='image_file1',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='image_file2',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='image_file3',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='image_file4',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Image 1'),
        ),
    ]
