# Generated by Django 3.0.4 on 2020-10-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
