# Generated by Django 3.0.4 on 2020-11-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='active_image',
            field=models.IntegerField(default=0),
        ),
    ]
