# Generated by Django 3.0.4 on 2020-09-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='MiniLocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.MiniLocation'),
            preserve_default=False,
        ),
    ]
