# Generated by Django 3.0.4 on 2020-12-01 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_files_active_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
