# Generated by Django 3.0.4 on 2020-10-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_files_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='icon_category',
            field=models.CharField(choices=[('1', 'Fashion'), ('2', 'Property'), ('3', 'Electronics'), ('4', 'Food & Restaurant'), ('5', 'Supermarket'), ('6', 'Service')], default='1', max_length=50),
        ),
    ]
