# Generated by Django 3.0.4 on 2021-08-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_files_designed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='designed_by',
        ),
    ]
