# Generated by Django 3.0.4 on 2021-07-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210723_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to='img/', verbose_name='Image 1')),
            ],
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='image_file2',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='image_file3',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='image_file4',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Image 4'),
        ),
    ]
