# Generated by Django 3.0.4 on 2020-09-30 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_files_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='location',
            field=models.URLField(blank=True, max_length=50000, verbose_name='Google Location URL'),
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
