# Generated by Django 3.0.4 on 2020-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_files_last_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/', verbose_name='Image 1')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codeword')),
                ('keyword', models.TextField()),
            ],
            options={
                'verbose_name': 'Image Resources',
                'verbose_name_plural': 'Image Resources',
            },
        ),
    ]
