# Generated by Django 3.0.4 on 2020-11-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_files_icon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='files',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='files',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Youtube Link'),
        ),
    ]
