# Generated by Django 3.0.4 on 2021-07-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210723_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Social Accounts',
                'verbose_name_plural': 'Social Accounts',
            },
        ),
    ]
