# Generated by Django 3.0.4 on 2021-01-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
    ]
