# Generated by Django 3.0.4 on 2021-08-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_shopdetails_designed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_purchase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='total_discount',
            field=models.IntegerField(default=0),
        ),
    ]
