# Generated by Django 3.0.4 on 2021-07-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_socialaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='minilocation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
