# Generated by Django 3.0.4 on 2021-01-04 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0005_files_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='rated_by',
            field=models.ManyToManyField(related_name='rated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='rating',
            field=models.FloatField(default=5, verbose_name='Rating'),
        ),
    ]
