# Generated by Django 3.0.4 on 2021-07-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_shopdetails_minilocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='covered_under_reward',
            field=models.BooleanField(default=False),
        ),
    ]
