# Generated by Django 3.0.4 on 2020-10-12 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20201003_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='activated_till',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
