# Generated by Django 3.0.4 on 2021-01-19 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0006_auto_20210104_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('total_coupon', models.IntegerField(default=5)),
                ('active', models.BooleanField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupons',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon History',
                'verbose_name_plural': 'Coupon History',
            },
        ),
    ]
