# Generated by Django 3.0.4 on 2021-07-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_shopdetails_covered_under_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='covered_under_monthly_reward',
            field=models.BooleanField(default=False),
        ),
    ]
