# Generated by Django 3.0.4 on 2020-10-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_files_activated_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statedata',
            name='cities',
            field=models.ManyToManyField(null=True, to='management.CityData'),
        ),
    ]
