# Generated by Django 3.0.4 on 2021-01-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20210119_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponhistory',
            name='coupon',
        ),
        migrations.AddField(
            model_name='couponhistory',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.Files'),
            preserve_default=False,
        ),
    ]
