# Generated by Django 3.0.4 on 2020-10-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20201016_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statedata',
            name='cities',
            field=models.ManyToManyField(blank=True, to='management.CityData'),
        ),
    ]
