# Generated by Django 3.0.4 on 2021-08-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_shopdetails_sales_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='forword_to_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
