# Generated by Django 3.0.4 on 2021-01-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20210124_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponhistory',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Files'),
        ),
    ]
