# Generated by Django 3.0.4 on 2020-10-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20201016_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Marketing Sources',
                'verbose_name_plural': 'Marketing Sources',
            },
        ),
    ]
