# Generated by Django 3.0.4 on 2021-08-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_shopdetails_forword_to_freelancer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdetails',
            old_name='forword_to_freelancer',
            new_name='forward_to_freelancer',
        ),
    ]
