# Generated by Django 3.0.4 on 2021-08-23 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20210823_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentissue',
            old_name='shop',
            new_name='offer',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 23, 9, 47, 17, 571073)),
        ),
    ]
