# Generated by Django 3.0.4 on 2021-02-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20210124_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
