# Generated by Django 3.0.4 on 2021-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_couponhistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponhistory',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
