# Generated by Django 3.0.4 on 2021-08-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20210803_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='design_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='final_pamphlet',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Final Design'),
        ),
    ]
