# Generated by Django 3.0.4 on 2021-08-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20210803_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='freelancer_profit',
            field=models.IntegerField(default=0),
        ),
    ]
