# Generated by Django 3.0.4 on 2021-02-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_couponhistory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Image'),
        ),
    ]
