# Generated by Django 3.0.4 on 2021-02-14 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
