# Generated by Django 3.0.4 on 2021-08-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_shopdetails_freelancer_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.PackageType'),
        ),
    ]
