# Generated by Django 3.0.4 on 2021-08-10 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20210809_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='business_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Category'),
        ),
    ]
