# Generated by Django 3.0.4 on 2021-03-07 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0014_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='rated_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='rated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
