# Generated by Django 3.0.4 on 2021-08-10 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20210810_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='business_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Category'),
        ),
    ]
