# Generated by Django 3.0.4 on 2021-03-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20210307_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponhistory',
            options={'verbose_name': 'All Coupon History', 'verbose_name_plural': 'All Coupon History'},
        ),
    ]
