# Generated by Django 3.0.4 on 2021-07-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_discount_shopdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='phone_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='whatsapp_number',
            field=models.CharField(max_length=1000),
        ),
    ]
