# Generated by Django 3.0.4 on 2021-07-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_shopdetails_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='image_file1',
            field=models.FileField(null=True, upload_to='shop-images/'),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='image_file2',
            field=models.FileField(null=True, upload_to='shop-images/'),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='image_file3',
            field=models.FileField(null=True, upload_to='shop-images/'),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='image_file4',
            field=models.FileField(null=True, upload_to='shop-images/'),
        ),
    ]
