# Generated by Django 3.0.4 on 2021-09-04 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_auto_20210902_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 4, 12, 45, 15, 165364)),
        ),
    ]
