# Generated by Django 3.0.4 on 2021-09-06 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20210904_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhamplateDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('design', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
            options={
                'verbose_name': 'Phamplate Design',
                'verbose_name_plural': 'Phamplate Design',
            },
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 6, 14, 38, 20, 729416)),
        ),
    ]
