# Generated by Django 3.0.4 on 2021-07-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20210712_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='comment1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='comment2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='comment3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='comment4',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
