# Generated by Django 3.0.4 on 2021-09-06 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_auto_20210906_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhamplateDesign',
            new_name='PamphletDesign',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 6, 14, 39, 48, 805620)),
        ),
    ]
