# Generated by Django 3.0.4 on 2021-09-07 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_auto_20210906_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='pamphletdesign',
            name='font_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 7, 10, 20, 34, 130555)),
        ),
    ]
