# Generated by Django 3.0.4 on 2021-07-20 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_shopdetails_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='date_of_registration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
