# Generated by Django 3.0.4 on 2021-07-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20210720_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
