# Generated by Django 3.0.4 on 2021-07-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_shopdetails_gst_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='invoice_pdf',
            field=models.FileField(null=True, upload_to='all-invoices/'),
        ),
    ]
