# Generated by Django 3.0.4 on 2021-09-08 10:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0028_auto_20210907_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pamphletdesign',
            name='heading',
        ),
        migrations.AddField(
            model_name='pamphletdesign',
            name='message',
            field=models.CharField(blank=True, max_length=100, verbose_name='Message on Pamphlet'),
        ),
        migrations.AddField(
            model_name='pamphletdesign',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title of Pamphlet'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 8, 15, 39, 9, 875976)),
        ),
        migrations.CreateModel(
            name='DownloadedDesigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Downloadable Designs',
                'verbose_name_plural': 'Downloadable Designs',
            },
        ),
    ]
