# Generated by Django 3.0.4 on 2021-07-22 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_shopdetails_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
