# Generated by Django 3.0.4 on 2021-09-10 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20210908_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadeddesigns',
            name='base_pamphlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.PamphletDesign'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 10, 15, 45, 13, 231944)),
        ),
        migrations.AlterField(
            model_name='pamphletdesign',
            name='design',
            field=models.ImageField(blank=True, help_text='Uploaded image dimention must be 750X800 pixels', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='pamphletdesign',
            name='message',
            field=models.CharField(blank=True, help_text='This message will get printed on the Pamphlet', max_length=100, verbose_name='Message on Pamphlet'),
        ),
    ]
