# Generated by Django 3.0.4 on 2021-09-16 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20210910_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 16, 11, 54, 12, 849634)),
        ),
    ]
