# Generated by Django 3.0.4 on 2021-09-29 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_auto_20210916_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Default Design')),
            ],
            options={
                'verbose_name': 'Default Design',
                'verbose_name_plural': 'Default Design',
            },
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 29, 19, 38, 25, 764346)),
        ),
    ]
