# Generated by Django 2.1 on 2021-12-05 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_auto_20211205_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='slider_image1',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Slider Image 1'),
        ),
        migrations.AddField(
            model_name='files',
            name='slider_image2',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Slider Image 2'),
        ),
        migrations.AddField(
            model_name='files',
            name='slider_image3',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Slider Image 3'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 5, 15, 16, 39, 146181)),
        ),
    ]
