# Generated by Django 2.1 on 2022-01-16 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_auto_20211214_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 16, 22, 4, 24, 484699)),
        ),
    ]
