# Generated by Django 2.1 on 2022-03-13 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_auto_20220116_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='pamphletdesign',
            name='copy_font_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 13, 19, 53, 11, 644980)),
        ),
    ]
