# Generated by Django 2.1 on 2022-03-13 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_auto_20220313_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='pamphletdesign',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 13, 22, 45, 8, 580515)),
        ),
    ]
